### PR TITLE
add masto.nyc

### PR DESCRIPTION
**Pull request by seano-vs**

### CODE REVIEW

**Comment by jazmichaelking** [comment]
This map is intended to help people find Mastodon members near them. As such, I only add servers with a reasonable population. I will leave the issue open and revisit from time to time, but please feel free to comment on this issue when your server hits 50 active users. In the meantime, please consider registering on https://masto.town/ - a database of regional instances

**Comment by stefanhayden** [comment]
they are at 55 now.

**Comment by seano-vs** [comment]
@jazmichaelking - Looks like @stefanhayden beat me to it.

**Comment by jazmichaelking** [comment]
The PR is for mastodon.nyc ,  the title is for masto.nyc ,  one of the domains looks like there's soem DNS issues, could you confirm which domain you want added

**Comment by seano-vs** [comment]
Oh, geeze. Apparently I'm an idiot. masto.nyc is the intended domain, haha. My bad! I'll fix it now

**Comment by seano-vs** [comment]
Aight, @jazmichaelking I think we're good to go!

**Pull request merged**
